name: Deploy

on:
  push: 
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key
        uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
        with:
          SSHKEY: ${{ secrets.SSH_KEY }}
          ORIGIN: python3.ninja
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x  
      - run: npm install
      - run: npm build
      - run: rsync --progress -v dist/* zodman@python3.ninja:apps/todo-ts/
