name: Deploy

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key
        uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
        with:
          SSHKEY: ${{ secrets.SSH_KEY }}
          ORIGIN: python3.ninja
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x  
      - run: yarn install -D
      - run: yarn  build
      - run: | 
          ssh-keyscan python3.ninja >> ~/.ssh/known_hosts
          rsync --recursive --progress -v build/* zodman@python3.ninja:apps/tsdo-ts/
